### ISSUE TITLE
Syntax error in BrickPi.py

### ISSUE THREAD

**Issue by jumaka** [DexterInd/BrickPi_Python#51]
There is a Syntax error in the BrickPi sensor examples. There is a list of 5 =

I have removed these and the code seems to run for my initial tests. I attach the git diff, happy to open a pull request.

'''python
--- a/Sensor_Examples/BrickPi.py
+++ b/Sensor_Examples/BrickPi.py
@@ -136,7 +136,7 @@ TYPE_SENSOR_EV3_COLOR_M2     = 52   # Color  // Min is 0, ma
 TYPE_SENSOR_EV3_COLOR_M3     = 53      # Raw reflected
 TYPE_SENSOR_EV3_COLOR_M4     = 54      # Raw Color Components
 TYPE_SENSOR_EV3_COLOR_M5     = 55      # Calibration???  Not currently implemen
-=======
+
 TYPE_SENSOR_EV3_COLOR_M0     = 50
 TYPE_SENSOR_EV3_COLOR_M1     = 51
 TYPE_SENSOR_EV3_COLOR_M2     = 52
'''

**Comment by DexterInd** [comment]
Hey Jumaka, sorry for the slow response on this.  I think I've just updated both files.  Can you please double check?  If the problem is solved, let me know!  Thanks!

**Comment by jumaka** [comment]
Pulled the revised code and tried one of the Sensor_Examples and the error has gone. Thanks @DexterInd
