### ISSUE TITLE
Line 139 BrickPi.py contains =======

### ISSUE THREAD

**Issue by mikemcfarlane** [DexterInd/BrickPi_Python#52]
Line 139 BrickPi.py contains =======, all copies of BrickPi.py, causes SyntaxError.

**Comment by DexterInd** [comment]
Thanks Mike sorry for the slopiness.  I don't know why, but when we did our last update, I think these were automatically added in by Github.

**Comment by DexterInd** [comment]
Closed it, then thought better.  Can you check and make sure this works for you now?

**Comment by mikemcfarlane** [comment]
I think it might have come from a merge conflict. Works for me with that line removed. Thanks.
