### ISSUE TITLE
Change License to GNU GPL3

### ISSUE THREAD

**Issue by DexterInd** [DexterInd/BrickPi_Python#54]
Hey folks,
We had a request to change this license from Creative Commons over to GNU GPL3.  I wanted to propose it and make sure everyone is ok with it before I make the change.  

http://www.gnu.org/licenses/gpl-3.0.txt

Please sound off!

**Comment by imtal** [comment]
As much of your software has the form of a library, I would expect LGPL which is copyleft towards the library itself but offers somewhat more freedom in its use.
