### ISSUE TITLE
Multiplexer for NXT/EV3 Motors (NXTMMX-v2)

### ISSUE THREAD

**Issue by BrickPiUser** [DexterInd/BrickPi_Python#57]
Hi,

i need more than four motors, so I'm looking for a Solution. Do you knwo, if its possible to use the Mindsensor's Multplexer NXTMMX-v2 with the "BrickPi.py"?
I think, this multiplexer is just an I²C extender. Mindsensors wrote me: "NXTMMX-v2 is an i2c device and it's programming interface is documented. Not sure if there is exposed I2C interface and API on BrickPi, 
but it would be possible to use NXTMMX-v2 using i2c interface."

Thanks!

**Comment by DexterInd** [comment]
Hey BrickPiUser, we don't know much about the Minsensors product.  If it runs on I2C though, it should not be a problem to connect to it via I2C on the BrickPi.

Are they an open source company?  Do they share their code?  Do they have any python code for the sensor?

**Comment by BrickPiUser** [comment]
There is open source code for drivers and samples for NXT, EV3 and Arduino. None for python.
The description shows how to control it via I2C. Its a I2C device whitch controls the motors. You can't use the motors directly via I2C. 
So I'm thinking I have to write my own drivers for that device? Does it work, if I take the functions "BrickPiTx", "BrickPiRx" and "BrickPiChangeAddress" from "Brickpi.py" for that?

**Comment by DexterInd** [comment]
Which language are you trying to write code for then?  

Do you have a link?  

We have examples for connecting I2c devices and I think we could help you (or try since we don't have the hardware) make a proper program to do this.

**Comment by BrickPiUser** [comment]
I'm trying to write in python.
Where can i find those examples?

Link mulitplexer:
http://www.mindsensors.com/index.php?module=pagemaster&PAGE_user_op=view_page&PAGE_id=134

description link:
http://www.mindsensors.com/index.php?module=documents&JAS_DocumentManager_op=downloadFile&JAS_File_id=1345

**Comment by DexterInd** [comment]
In python there's a great example here:

https://github.com/DexterInd/BrickPi_Python/blob/master/Sensor_Examples/dIMU_on_Sensor_5.py

You can see that it uses the Port 5, which links directly into the Pi SMBUS, which will make it a little easier to write the I2C for.
