### ISSUE TITLE
no module ir_receiver_check

### ISSUE THREAD

**Issue by mpahrens** [DexterInd/BrickPi_Python#59]
When installing against the latest master, import BrickPi fails due to ImportError "no module ir_receiver_check". I see this was added to BrickPi, but was it added to the setup easy_install? If not, how can I install it by hand. Thanks!

**Comment by karan259** [comment]
the newer version of the BrickPi library checks if the IR receiver is being used because it uses the Serual pins. We are still updating the image, you can simply use the ir_receiver_check.py library from here and add it in the same folder as the BrickPi https://github.com/DexterInd/GoBox/tree/master/LIRC_GUI

**Comment by mpahrens** [comment]
Ok, that works for me. I just didn't know where it come from. Feel free to close this issue if you like.

**Comment by dolonnen** [comment]
Sorry, why don't you put this module in the BrickPi_Python repository?

**Comment by MattBrauer** [comment]
It's a little bit annoying to have to track a new dependency down to a different project's repository. Would you please add it to the BrickPi repository?

**Comment by karan259** [comment]
We just updated the **setup.py** in the main BrickPi Python repository in Pull #62 which would install the  ir_receiver_check library too. Can you run: `sudo python setup.py install` in the main BrickPi python folder [here](https://github.com/DexterInd/BrickPi_Python) which should resolve the problem.

**Comment by tswiftma** [comment]
Hi, I followed the above steps to update but when I then try to run simplebot_simple.py I get the error "Disable IR receiver before continuing". I created my image on Monday, still trying to get something to run!

Also can you specify which Linux directories to run the commands? Thanks

**Comment by DexterInd** [comment]
Did you run the script @karan259 wrote for disabling this?

**Comment by tswiftma** [comment]
Which script are you referring to? I uninstalled BrickPi then reinstalled. When I run the ir_receiver check scripts I get the value "true". How do I disable it? Thanks

pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python simplebot_simple.py 
Disable IR receiver before continuing
pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python ir_receiver_check.py
True
pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python ir_receiver_check.pyc
True
pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python simplebot_simple.py 
Disable IR receiver before continuing

**Comment by tswiftma** [comment]
Hello? This is pretty frustrating. I'm not a Linux expert. I think that basic examples should work out of the box...

**Comment by DexterInd** [comment]
We wrote a tutorial on how to do this with the latest image.  It doesn't require expertise in Linux.  This issue is resolved here:  http://www.dexterindustries.com/howto/enable-or-disable-brickpi-communications/

**Comment by tswiftma** [comment]
The solution worked thanks so much :-)

**Comment by DexterInd** [comment]
Our pleasure!  I will be publishing a new image soon that makes this the default.  Thanks for the heads up on the problem, I appreciate it!

**Comment by jsulaiman** [comment]
After I updated firmware and brickpi3, I cannot find the icon to disable IR receiver setup anymore...
