### ISSUE TITLE
Installation stopped working`

### ISSUE THREAD

**Issue by michalvi** [DexterInd/BrickPi_Python#61]
Hello, since the merge of the https://github.com/DexterInd/BrickPi_Python/pull/58 pull request the installation process got disrupted.

When you try `import BrickPi` there appears an error saying `cannot import ir_receiver_check`.

If you revert this merge, everything works fine.

**Comment by DexterInd** [comment]
You can revert it; this is supposed to be a check on the serial line though to make sure it's not blocked.  It's important to do this or you might end up getting no response from the BrickPi.

**Comment by karan259** [comment]
We just updated the setup.py in the main BrickPi Python repository in Pull #62 which would install the  ir_receiver_check library too. Can you run: `sudo python setup.py install` in the main BrickPi python folder [here](https://github.com/DexterInd/BrickPi_Python) which should resolve the problem.

**Comment by michalvi** [comment]
Thank you @karan259, that's what I was hoping for!
