### ISSUE TITLE
Disable IR receiver before continuing

### ISSUE THREAD

**Issue by tswiftma** [DexterInd/BrickPi_Python#63]
I uninstalled BrickPi then reinstalled with the latest bits . When I run a sample python script I get the message "Disable IR receiver before continuing". Has anyone seen this? Tried running the ir_receiver_check.py scripts and I'm still hitting the problem.

pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python simplebot_simple.py 
Disable IR receiver before continuing
pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python ir_receiver_check.py
True
pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python ir_receiver_check.pyc
True
pi@dex ~/Desktop/BrickPi/BrickPi_Python $ sudo python simplebot_simple.py 
Disable IR receiver before continuing

**Comment by DexterInd** [comment]
This issue can be resolved by following the steps here:

http://www.dexterindustries.com/howto/enable-or-disable-brickpi-communications/
