### ISSUE TITLE
NXT Ultrasonic Sensor Drivers not Working

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi_Python#81]
The Ultrasonic drivers are not working at all. I first created a program to test the sensor and got readings from 980 to 110, and they were pretty much at random. I then tried the default test program, LEGO-UltraSonic_sensor_Test.py, and got a readout like this: -1, -1 -1, and so on.
I then tried the C# version and the drivers work great, very accurate.
I have done a great deal of testing, including switching cables, ports, and such, I think I have pretty much ruled out that it is not a hardware issue. It most likely is an issue with the python drivers.

**Comment by DexterInd** [comment]
Hey graykevinb, we were using these just last week and everything worked just fine.  Are you running Raspbian for robots?

**Comment by mattallen37** [comment]
Have you updated to the latest version of the drivers? There have been some communication improvements made recently.

**Comment by graykevinb** [comment]
Yes, I have been running rasbian for robots, actually I have been using pretty much everything from the kit.
I will try updating the drivers.

**Comment by graykevinb** [comment]
The update fixed it, works like a dream, I appreciate all your help. :)

**Comment by DexterInd** [comment]
So glad to hear it!
