### ISSUE TITLE
Pi 3 Inappropriate ioctl for device

### ISSUE THREAD

**Issue by burf2000** [DexterInd/BrickPi_Python#82]
So I have just put my BrickPi shield on My Pi3, downloaded the latest Raspbian
Done sudo update, Upgrade etc

Cloned BrickPi_Python
And tried to run sudo python LEGO-Touch_Sensor_Test.py

I get :

BrickPiSetupSensors()   #Send the properties of sensors to BrickPi
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 492, in BrickPiSetupSensors
    BrickPiFlush() # Toss out any old Rx data. This helps to make sure everything is fresh, and for the correct "core".
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 697, in BrickPiFlush
    while ser.inWaiting():
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
IOError: [Errno 25] Inappropriate ioctl for device

**Comment by burf2000** [comment]
I have made sure I2C is enabled

**Comment by burf2000** [comment]
I am now running it on 9v and still erroring

**Comment by mattallen37** [comment]
If you're using Raspbian instead of Raspbian For Robots, the UART will need to be configured to be usable by the BrickPi Python drivers. [This script](https://github.com/DexterInd/BrickPi/blob/master/Setup%20Files/install.sh) should do the necessary configuration, but I recommend that you use [Raspbian For Robots](https://www.dexterindustries.com/raspberry-pi-robot-software/) which is already configured for the Dexter Industries robots.

**Comment by burf2000** [comment]
I wanted to install ROS so I went with the normal Raspbain

Output 
I2C-dev already there
i2c-bcm2708 already there
spi-dev already there
Setting up i2c speed...
gpio: Unable to load/unload modules as this Pi has the device tree enabled.
  You need to run the raspi-config program (as root) and select the
  modules (SPI or I2C) that you wish to load/unload there and reboot.
  There is more information here:
      https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=97314
Setting up UART clock speed...
Clock speed already configured
Enabling serial pins...
sed: can't read /etc/inittab: No such file or directory
Disabling Serial Port Login...
Already Disabled
python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by mattallen37** [comment]
The setup.py file can be found [here](https://github.com/DexterInd/BrickPi/blob/master/Setup%20Files/setup.py).

**Comment by burf2000** [comment]
Sorry whats that for?  I am trying to get a sample to work?

**Comment by burf2000** [comment]
I run sudo python setup.py install and seems to work? but samples still dont work

**Comment by burf2000** [comment]
I have not got passed this error and have ImportError: No module named ir_receiver_check

**Comment by burf2000** [comment]
Nope back to Traceback (most recent call last):
  File "LEGO-Touch_Sensor_Test.py", line 26, in <module>
    BrickPiSetupSensors()   #Send the properties of sensors to BrickPi
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 492, in BrickPiSetupSensors
    BrickPiFlush() # Toss out any old Rx data. This helps to make sure everything is fresh, and for the correct "core".
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 697, in BrickPiFlush
    while ser.inWaiting():
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
IOError: [Errno 25] Inappropriate ioctl for device

**Comment by burf2000** [comment]
sudo i2cdetect -y -q 1 displays nothing

**Comment by mattallen37** [comment]
The BrickPi uses UART rather than I2C for communication between the Raspberry Pi and the onboard microcontrollers.

**Comment by burf2000** [comment]
So I2C should be off?

**Comment by mattallen37** [comment]
No, you can leave I2C enabled.

Can you try using the Raspbian For Robots image, and see if that works?

This message `File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
IOError: [Errno 25] Inappropriate ioctl for device` is not something I remember having seen before. I'm pretty sure it's related to the UART configuration, and I know that UART is configured properly on the Raspbian For Robots image.

**Comment by CleoQc** [comment]
Did you run the install script?

**Comment by burf2000** [comment]
Your image works fine, I did run install.sh and setup.py

**Comment by DexterInd** [comment]
Are you starting with Raspbian Jessie with Pixel or Jessie Lite?  https://www.raspberrypi.org/downloads/raspbian/

**Comment by burf2000** [comment]
Raspbian Jessie with Pixel

**Comment by DexterInd** [comment]
Ok, we will start there and see if we can see the same problem.

**Comment by Shoban94** [comment]
Hi @burf2000 ,

We tried with the new Raspbian Jessie Pixel and we have it working. I would encourage you to go through the steps below and try out them and post the error if you get any.
1) sudo apt-get update
2) sudo apt-get upgrade -y
3) Edit the boot config with
    - 1. sudo nano /boot/config.txt
    - 2. add "dtoverlay=pi3-disable-bt" to the end of the file
    - 3. save the file
    - 4. run "sudo systemctl disable hciuart" to prevent BT modem from attempting to use UART
    - 5. reboot raspberry pi
4)  sudo git clone http://www.github.com/DexterInd/BrickPi.git
5)  cd BrickPi/Setup\ Files
6)  sudo bash install.sh
7)  sudo pip install - U future
8)  sudo git clone http://www.github.com/DexterInd/BrickPi_Python.git
9)  sudo apt-get install python-setuptools python-dev build-essential
10) cd BrickPi_Python
11) sudo python setup.py install
12) cd Sensor Examples
and try running an example
if you get any import BrickPi no module found or import Ir_receiver_check no module found errors,
repeat step 11.

Please tell us if this works,
-Shoban

**Comment by burf2000** [comment]
Hi Shoban I will try this tonight, where was the information about the BT listed?

**Comment by DexterInd** [comment]
The information about the BT wasn't listed in the BrickPi setup; it was buried in our code update for the Pi3, and has to do with the hardware changes made to the Pi to support the BT module.

**Comment by DexterInd** [comment]
I actually stand corrected by @Shoban94 , the information is already published here:  https://github.com/DexterInd/BrickPi/blob/master/Setup%20Files/README
In the readme under setup.

**Comment by burf2000** [comment]
Could I suggest you put it on https://www.dexterindustries.com/BrickPi/getting-started/pi-prep/ under Modify your own image:  :)  I am still at work but will try it tonight

**Comment by burf2000** [comment]
I have done your guide and mine just sits at sudo python LEGO-Touch_Sensor_Test.py  with nothing happening a tall

I will re flash the image and start again

**Comment by burf2000** [comment]
sudo pip install - U future
Downloading/unpacking -
  Real name of requirement - is 1
  Could not find any downloads that satisfy the requirement -
Cleaning up...
No distributions at all found for -
Storing debug log for failure in /root/.pip/pip.log

**Comment by CleoQc** [comment]
No space between the - and the U?

**Comment by burf2000** [comment]
Well its kinda working
It works for a few seconds, pauses prints out
('Unexpected error: ', <type 'exceptions.OSError'>)
('Unexpected error: ', <class 'serial.serialutil.SerialException'>)

Works for a bit then dies with

OSError: [Errno 11] Resource temporarily unavailable

**Comment by burf2000** [comment]
I ran it again and got

Traceback (most recent call last):
  File "Sensor_Examples/LEGO-Touch_Sensor_Test.py", line 29, in <module>
    result = BrickPiUpdateValues()  # Ask BrickPi to update values for sensors/motors 
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 584, in BrickPiUpdateValues
    result, BytesReceived, InArray = BrickPiRx(0.007500) #check timeout
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 732, in BrickPiRx
    while( ser.inWaiting() <= 0):
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
IOError: [Errno 5] Input/output error

**Comment by burf2000** [comment]
I have not enabled any settings in Raspi-config (i2c, spi, serial, GPIO remote etc)

**Comment by burf2000** [comment]
I reran the install.sh and sudo python setup.py install and rebooted and still get 

1
1
('Unexpected error: ', <type 'exceptions.OSError'>)
1
('Unexpected error: ', <type 'exceptions.OSError'>)
Traceback (most recent call last):
  File "Sensor_Examples/LEGO-Touch_Sensor_Test.py", line 29, in <module>
    result = BrickPiUpdateValues()  # Ask BrickPi to update values for sensors/motors 
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 581, in BrickPiUpdateValues
    BrickPiFlush() # Toss out any old Rx data. This helps to make sure everything is fresh, and for the correct "core".
  File "/home/pi/BrickPi_Python/Sensor_Examples/BrickPi.py", line 699, in BrickPiFlush
    ser.read(ser.inWaiting())
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 453, in read
    buf = os.read(self.fd, size-len(read))
OSError: [Errno 11] Resource temporarily unavailable

**Comment by DexterInd** [comment]
After a little more debugging, we've modified the directions with two more steps.  You should be able to just make these two changes:

run `sudo raspi-config` and go to "7 Advanced Options" -->  "A8 Serial" -->  And then select "No" 

Then, modify /boot/config.txt to `enable_uart=1`  (This line should be there from the previous install, but set to 0 from the raspi-config commands.  

Reboot.

**Comment by DexterInd** [comment]
For future reference, we put the serial lines on logic analyzer and saw the Raspberry Pi Login flash by, this was what was causing the interruption, and the io errors.

**Comment by burf2000** [comment]
Seems to work fine now thank you!
